ecommerce/demo/urls.py
from django.urls import path
from . import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category, name="category"),
    path("product-by-category/<slug:category>/", views.product_by_category, name="product_by_category"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include("ecommerce.demo.urls",namespace='demo') )
]

ecommerce/demo/views.py
from django.shortcuts import render
from ecommerce.inventory import models


def home(request):
    return render(request, "index.html")


def category(request):
    data = models.Category.objects.all()

    return render(request, "categories.html", {"data": data})


def product_by_category(request, category):
    data = models.Product.objects.filter(category__name=category).values(
        "id", "name", "slug", "product__store_price",
    )
    # print(data)
    return render(request, "product_by_category.html", {"data": data})


def product_detail(request, slug):
    filter_arguments = []
    from django.db.models import Count
    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)
        data = models.ProductInventory.objects.filter(product__slug=slug). \
            filter(attribute_values__attribute_value__in=filter_arguments).annotate(
            num_tags=Count('attribute_values')).filter(num_tags=len(filter_arguments)).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units")
    else:
        data = models.ProductInventory.objects.filter(product__slug=slug). \
            filter(is_default=True).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units")
    print(data)
    y = models.ProductInventory.objects.filter(product__slug=slug).distinct().values(
        "attribute_values__product_attribute__name", "attribute_values__attribute_value")
    z = models.ProductTypeAttributes.objects.filter(product_type__product_type__product__slug=slug).values(
        "product_attribute__name").distinct()
    print(z)

    return render(request, "product_detail.html", {"data": data, "y": y, "z": z})

ecommerce/demo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Hello, world!</title>
  </head>
  <body>

    {% block content %}{% endblock content %}

  </body>
</html>

ecommerce/demo/templates/categories.html
{% extends 'base.html' %}

{% block content %}
<h1>Categories</h1>
{% for x in data %}
<a href="{% url 'demo:product_by_category' category=x.slug %}">{{x.name}}</a>

{% endfor %}

{% endblock content %}

ecommerce/demo/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Homepage</h1>
<a href="{% url 'demo:category' %}"> Categories </a>
{% endblock content %}

ecommerce/demo/templates/product_by_category.html
{% extends 'base.html' %}

{% block content %}
<ul>
{% for x in data %}
<li>{{x.name}} <a href="{% url 'demo:product_detail' slug=x.slug %}" >view</a>
</li>
<li>{{x.id}}</li>
<li>Price: $ {{x.product__store_price}}</li>
<h1>---------</h1>
{% endfor %}
</ul>
{% endblock content %}

ecommerce/demo/templates/product_detail.html
Product Detail

<ul>
    {% for x in data %}

    <li>{{x.product__name}}</li>
    <li>{{x.sku}}</li>
    <li>{{x.product_inventory__units}}</li>

    {% endfor %}
</ul>

{% for x in z %}
{{x.product_attribute__name}}
    {% for a in y %}
        {% if a.attribute_values__product_attribute__name == x.product_attribute__name %}
        <li> {{a.attribute_values__product_attribute__name}}: {{a.attribute_values__attribute_value}} </li>
        {% endif %}
    {% endfor %}
{% endfor %}